{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lsio-common.serviceAccountName" . }}
  labels:
{{ include "lsio-common.labels" . | nindent 4 }}
{{- end -}}
