apiVersion: v1
kind: Service
metadata:
  name: {{ include "lsio-common.fullname" . }}
  labels:
    {{- include "lsio-common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portName }}
  selector:
    {{- include "lsio-common.selectorLabels" . | nindent 4 }}
