apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lsio-common.fullname" . }}
  labels:
    {{- include "lsio-common.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "lsio-common.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lsio-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lsio-common.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "lsio-common.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "lsio-common.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.containerPort }}
              protocol: {{ .Values.service.protocol }}
          env:
          - name: PUID
            value: {{ .Values.lsioCommon.puid | quote }}
          - name: PGID
            value: {{ .Values.lsioCommon.pgid | quote }}
          - name: TZ
            value: {{ .Values.lsioCommon.tz | quote }}
        {{- range $key, $value := .Values.environment }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.environmentFromSecret }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $value.name }}
                key: {{ $value.key }}
          {{- end }}
        {{- if .Values.hostPaths }}
          volumeMounts:
        {{- range $key, $value := .Values.hostPaths }}
          - name: {{ $key }}
            mountPath: {{ index (splitList ":" $value) 1 }}
        {{- end }}
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.hostPaths }}
      volumes:
    {{- range $key, $value := .Values.hostPaths }}
        - name: {{ $key }}
          hostPath:
            path: {{ index (splitList ":" $value) 0 }}
    {{- end }}
    {{- end }}
