apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: wireguard
      port: {{ .Values.wireguard.port}}
      nodePort: {{ .Values.wireguard.serverPort }}
      targetPort: wireguard
      protocol: UDP
  selector:
    {{- include "wireguard.selectorLabels" . | nindent 4 }}
