apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-socks
  labels:
  {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: socks-tcp
      port: {{ .Values.privateInternetAccess.shadowSocksPort }}
      targetPort: socks-tcp
      protocol: TCP
    - name: socks-udp
      port: {{ .Values.privateInternetAccess.shadowSocksPort }}
      targetPort: socks-udp
      protocol: UDP
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
