apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bazarr.fullname" . }}
  labels:
    {{- include "bazarr.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "bazarr.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bazarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bazarr.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bazarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.bazarr.port }}
              protocol: TCP
          env:
            - name: PUID
              value: {{ .Values.bazarr.puid | quote }}
            - name: PGID
              value: {{ .Values.bazarr.pgid | quote }}
            - name: TZ
              value: {{ .Values.bazarr.tz | quote }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies
              mountPath: /movies
            - name: tv
              mountPath: /tv
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.bazarr.config.hostPath }}
        - name: movies
          hostPath:
            path: {{ .Values.bazarr.movies.hostPath }}
        - name: tv
          hostPath:
            path: {{ .Values.bazarr.tv.hostPath }}
