apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "readarr.fullname" . }}
  labels:
    {{- include "readarr.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "readarr.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "readarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "readarr.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "readarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.readarr.port }}
              protocol: TCP
          env:
            - name: PUID
              value: {{ .Values.readarr.puid | quote }}
            - name: PGID
              value: {{ .Values.readarr.pgid | quote }}
            - name: TZ
              value: {{ .Values.readarr.tz | quote }}
            - name: UMASK
              value: {{ .Values.readarr.umask | quote }}
            - name: DEBUG
              value: {{ .Values.readarr.debug | quote }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: books
              mountPath: /books
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.readarr.configHostPath }}
        - name: downloads
          hostPath:
            path: {{ .Values.readarr.downloadsHostPath }}
        - name: books
          hostPath:
            path: {{ .Values.readarr.booksHostPath }}
