repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: kubernetes-dashboard
  url: https://kubernetes.github.io/dashboard
#- name: bitnami
#  url: https://charts.bitnami.com/bitnami
#- name: jetstack
#  url: https://charts.jetstack.io
#- name: mojo2600
#  url: https://mojo2600.github.io/pihole-kubernetes

helmDefaults:
  createNamespace: true
  atomic: true
  verify: true

templates:
  default: &default
    namespace: "{{ `{{ .Release.Name }}` }}"
    labels:
      release: "{{ `{{ .Release.Name }}` }}"
    values:
    - "./values/{{ `{{ .Release.Name }}` }}.yaml"

releases:
- name: kubernetes-dashboard
  <<: *default
  chart: kubernetes-dashboard/kubernetes-dashboard
  version: 2.7.1
  values:
  - protocolHttp: true
    rbac:
      clusterReadOnlyRole: true
