---
apiVersion: v1
kind: Namespace
metadata:
  name: jackett
spec: {}

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jackett
  namespace: kube-system
spec:
  repo: https://pbar1.github.io/containers
  chart: jackett
  version: 0.0.0
  targetNamespace: jackett
  valuesContent: |-
    ingress:
      enabled: true
      hosts:
      - host: ubuntu
        paths:
        - /jackett
    jackett:
      tz: America/Los_Angeles
      config:
        hostPath: /data/docker/jackett
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 512Mi
