---
apiVersion: v1
kind: Namespace
metadata:
  name: transmission
spec: {}

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: transmission
  namespace: kube-system
spec:
  repo: https://pbar1.github.io/containers
  chart: transmission
  version: 0.0.0
  targetNamespace: transmission
  valuesContent: |-
    ingress:
      enabled: true
      hosts:
      - host: ubuntu
        paths:
        - /transmission
    transmission:
      tz: America/Los_Angeles
      config:
        hostPath: /data/docker/transmission
      downloads:
        hostPath: /data/downloads
    privateInternetAccess:
      credentialsSecret: private-internet-access-credentials
      extraSubnets: 192.168.1.0/24
      tz: America/Los_Angeles
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 512Mi
