name: ci

on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 8 * * *" # Daily at 08:00 UTC (midnight PST)

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push (lidarr)
      uses: docker/build-push-action@v5
      with:
        file: lidarr.Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/pbar1/lidarr:latest

    - name: Build and push (prowlarr)
      uses: docker/build-push-action@v5
      with:
        file: prowlarr.Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/pbar1/prowlarr:latest

    - name: Build and push (radarr)
      uses: docker/build-push-action@v5
      with:
        file: radarr.Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/pbar1/radarr:latest

    - name: Build and push (readarr)
      uses: docker/build-push-action@v5
      with:
        file: readarr.Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/pbar1/readarr:latest

    - name: Build and push (sonarr)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: sonarr.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/pbar1/sonarr:latest
